### PR TITLE
 Potions BAM and PLAT98

### PR DESCRIPTION
**Pull request by TotoR115**
- component 200 : Core content patches update inventory's bam of potion without updating description's bam + fix a regression of v4.2.0
- Component 113 : Smart Avatar & Armour Switching should not update PLAT98 to stay faithful to BG1 phoenix guard (it is a mage animation for pheoarch.cre)

### CODE REVIEW

**Comment by skellytz** [comment]
Thank you! I'll look into these. What do you mean by "regression of v4.2.1" with regard to component 200? v4.2.1 didn't introduce any changes to this component.

**Comment by TotoR115** [comment]
If you look at ini:
https://github.com/SpellholdStudios/1pp/blob/867a7e8c8d8aee1ac7f5b2bed38bdfbb5beb59c0/1pp/1pp-config-default.ini#L41
https://github.com/SpellholdStudios/1pp/blob/867a7e8c8d8aee1ac7f5b2bed38bdfbb5beb59c0/1pp/1pp-config-default.ini#L43
But in C200:
https://github.com/SpellholdStudios/1pp/blob/867a7e8c8d8aee1ac7f5b2bed38bdfbb5beb59c0/1pp/components/200_1ppv2_cut.tph#L977

It is the opposit and has been introduce:
https://github.com/SpellholdStudios/1pp/commits/master/1pp/components/200_1ppv2_cut.tph

**Comment by skellytz** [comment]
Thanks! That's what got me confused. Just to clarify: this was changed in v4.2.0, not v4.2.1

**Comment by TotoR115** [comment]
> Thanks! That's what got me confused. Just to clarify: this was changed in v4.2.0, not v4.2.1

Sorry, the fist post has been updated accordingly

**Pull request merged**
